baseurl: "/junu" # the subpath of your site, e.g. /blog
url: "https://junrepository.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

# encoding:
#   charset: UTF-8

paginate: 6
#한 페이지에 보이는 post수 
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

favicon: images/01.jpg

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed